<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>JsonAssetDataEditor</AssemblyName>
    <RootNamespace>JsonAssetDataEditor</RootNamespace>
    <ApplicationIcon Condition="Exists('app.ico')">app.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
